//
//  GuideEvent.h
//  BotDota
//
//  Created by xyh on 15/8/10.
//
//

#define ADD_LISTENER(name, func)     Director::getInstance()->getEventDispatcher()->addCustomEventListener(name, func)
#define REMOVE_LISTENER(name)        Director::getInstance()->getEventDispatcher()->removeCustomEventListeners(name)
#define DISPATCH_EVENT(name)         Director::getInstance()->getEventDispatcher()->dispatchCustomEvent(name)
#define DISPATCH_EVENT_WITH_USERDATA(name, data)         Director::getInstance()->getEventDispatcher()->dispatchCustomEvent(name, data)

#define GUIDE_LAYER_ZORDER  10000
#define GUIDE_LAYER_TAG     999888


// event name
#define GUIDE_EVENT_TOUCH_IN_RECT       "GUIDE_EVENT_TOUCH_IN_RECT"
#define GUIDE_EVENT_OUT_OF_RECT         "GUIDE_EVENT_OUT_OF_RECT"

#define GUIDE_EVENT_BEGIN_GUIDE         "GUIDE_EVENT_BEGIN_GUIDE"
#define GUIDE_EVENT_CONTENUE            "GUIDE_EVENT_CONTENUE"
#define GUIDE_EVENT_WAIT                "GUIDE_EVENT_WAIT"
#define GUIDE_EVENT_TALK_TOUCH          "GUIDE_EVENT_TALK_TOUCH"


// flag
#define GUIDE_FLAG_IS_NOT_FIRST_GUIDE          "GUIDE_FLAG_IS_NOT_FIRST_GUIDE"


// theme
#define GUIDE_THEME_SUMMON          "summon"
#define GUIDE_THEME_HEROLIST        "herolist"
#define GUIDE_THEME_FRIEND          "friend"


// cliping
#define GUIDE_CLIPING_BTN_HEROLIST                  "GUIDE_CLIPING_BTN_HEROLIST"
#define GUIDE_CLIPING_BATTLE_TIP                    "GUIDE_CLIPING_BATTLE_TIP%d"
#define GUIDE_CLIPING_BATTLE_TIP_GET_REWARD         "GUIDE_CLIPING_BATTLE_TIP_GET_REWARD"
#define GUIDE_CLIPING_BATTLE_REWARD_SURE            "GUIDE_CLIPING_BATTLE_REWARD_SURE"
#define GUIDE_CLIPING_BATTLE_TIP_CHALLENGE          "GUIDE_CLIPING_BATTLE_TIP_CHALLENGE"
#define GUIDE_CLIPING_BATTLE_BACK                   "GUIDE_CLIPING_BATTLE_BACK"
#define GUIDE_CLIPING_HALL_SECOND_MAP               "GUIDE_CLIPING_HALL_SECOND_MAP"
#define GUIDE_CLIPING_HALL_DISPATCHE_TEAM_FIRSRT    "GUIDE_CLIPING_HALL_DISPATCHE_TEAM_FIRSRT"
#define GUIDE_CLIPING_HALL_DISPATCHE_BTN            "GUIDE_CLIPING_HALL_DISPATCHE_BTN"
#define GUIDE_CLIPING_HALL_DISPATCHE_VIEW_BTN       "GUIDE_CLIPING_HALL_DISPATCHE_VIEW_BTN"
#define GUIDE_CLIPING_HALL_DISPATCHE_SURE           "GUIDE_CLIPING_HALL_DISPATCHE_SURE"
#define GUIDE_CLIPING_BTN_SUMMON                    "GUIDE_CLIPING_BTN_SUMMON"
#define GUIDE_CLIPING_DIALOG_SEE                    "GUIDE_CLIPING_DIALOG_SEE"
#define GUIDE_CLIPING_SUMMON_MASK                   "GUIDE_CLIPING_SUMMON_MASK"
#define GUIDE_CLIPING_SUMMON_BTN_SURE               "GUIDE_CLIPING_SUMMON_BTN_SURE"
#define GUIDE_CLIPING_SUMMON_BTN_CHANGE_RIGHT       "GUIDE_CLIPING_SUMMON_BTN_CHANGE_RIGHT"
#define GUIDE_CLIPING_SUMMON_BTN_BACK               "GUIDE_CLIPING_SUMMON_BTN_BACK"
#define GUIDE_CLIPING_HEROLIST_HERO_HEAD            "GUIDE_CLIPING_HEROLIST_HERO_HEAD"
#define GUIDE_CLIPING_HEROLIST_BTN_UPGRADE_RECT     "GUIDE_CLIPING_HEROLIST_BTN_UPGRADE_RECT"
#define GUIDE_CLIPING_HEROLIST_BTN_UPGRADE_ROUND    "GUIDE_CLIPING_HEROLIST_BTN_UPGRADE_ROUND"
#define GUIDE_CLIPING_HEROLIST_BTN_GO_BATTLE        "GUIDE_CLIPING_HEROLIST_BTN_GO_BATTLE"
#define GUIDE_CLIPING_HEROLIST_BTN_STAR_UP_RECT     "GUIDE_CLIPING_HEROLIST_BTN_STAR_UP_RECT"
#define GUIDE_CLIPING_HEROLIST_BTN_STAR_UP          "GUIDE_CLIPING_HEROLIST_BTN_STAR_UP"
#define GUIDE_CLIPING_HEROLIST_BTN_EQUIP_UP_RECT    "GUIDE_CLIPING_HEROLIST_BTN_EQUIP_UP_RECT"
#define GUIDE_CLIPING_HEROLIST_BTN_EQUIP_UP         "GUIDE_CLIPING_HEROLIST_BTN_EQUIP_UP"
#define GUIDE_CLIPING_HEROLIST_BTN_RUNE             "GUIDE_CLIPING_HEROLIST_BTN_RUNE"
#define GUIDE_CLIPING_HEROLIST_BTN_RUNE             "GUIDE_CLIPING_HEROLIST_BTN_RUNE"
#define GUIDE_CLIPING_BTN_HEROLIST_HEAD_MOVE_FIRST  "GUIDE_CLIPING_BTN_HEROLIST_HEAD_MOVE_FIRST"
#define GUIDE_CLIPING_BTN_HEROLIST_HEAD_MOVE_SEC    "GUIDE_CLIPING_BTN_HEROLIST_HEAD_MOVE_SEC"
#define GUIDE_CLIPING_BATTLE_BTN_INVADE             "GUIDE_CLIPING_BATTLE_BTN_INVADE"
#define GUIDE_CLIPING_BATTLE_BTN_INVADE_SEARCH      "GUIDE_CLIPING_BATTLE_BTN_INVADE_SEARCH"
#define GUIDE_CLIPING_BATTLE_BTN_INVADE_HEAD        "GUIDE_CLIPING_BATTLE_BTN_INVADE_HEAD"
#define GUIDE_CLIPING_BATTLE_BTN_INVADE_BEGINE      "GUIDE_CLIPING_BATTLE_BTN_INVADE_BEGINE"
#define GUIDE_CLIPING_BTN_FRIEND                    "GUIDE_CLIPING_BTN_FRIEND"
#define GUIDE_CLIPING_BATTLE_SPINE_REWARD           "GUIDE_CLIPING_BATTLE_SPINE_REWARD"


// IndependentGuide
#define HeroModule                      "HeroModule"
#define BattleModule                    "BattleModule"
#define FriendsModule                   "FriendsModule"
#define BlackMarketModule               "BlackMarketModule"
#define SynthesisModule                 "SynthesisModule"
#define OrderModule                     "OrderModule"
#define JJCModule                       "JJCModule"
#define AdventureModule                 "AdventureModule"
#define EndlessTowerModule              "EndlessTowerModule"


